-- MySQL Script generated by MySQL Workbench
-- 24 يول, 2018 EEST 08:18:27 م
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `isModerator` INT NOT NULL,
  `photoUrl` VARCHAR(45) NULL,
  `educationText` TEXT(1000) NULL,
  `jobExperienceText` TEXT(1000) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Connection` (
  `idConnection` INT NOT NULL AUTO_INCREMENT,
  `conncetedUserId` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idConnection`, `User_idUser`),
  INDEX `fk_Connections_Users_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Connections_Users`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ConnectionRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ConnectionRequest` (
  `idConnectionRequest` INT NOT NULL,
  `senderId` INT NOT NULL,
  `timeOfRequest` VARCHAR(45) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idConnectionRequest`, `User_idUser`),
  INDEX `fk_ConnectionRequests_Users1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_ConnectionRequests_Users1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Article` (
  `idArticle` INT NOT NULL,
  `uploadTime` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `contentText` TEXT(3000) NULL,
  `photoUrl` VARCHAR(45) NULL,
  `soundUrl` VARCHAR(45) NULL,
  `videoUrl` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idArticle`, `User_idUser`),
  INDEX `fk_Article_Users1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Article_Users1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `idComment` INT NOT NULL,
  `uploadTime` DATETIME NOT NULL,
  `contentText` TEXT(500) NULL,
  `Article_idArticle` INT NOT NULL,
  `Article_User_idUser` INT NOT NULL,
  PRIMARY KEY (`idComment`, `Article_idArticle`, `Article_User_idUser`),
  INDEX `fk_Comment_Article1_idx` (`Article_idArticle` ASC, `Article_User_idUser` ASC),
  CONSTRAINT `fk_Comment_Article1`
    FOREIGN KEY (`Article_idArticle` , `Article_User_idUser`)
    REFERENCES `mydb`.`Article` (`idArticle` , `User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Interest` (
  `idInterest` INT NOT NULL,
  `interestDate` DATETIME NOT NULL,
  `Article_idArticle` INT NOT NULL,
  `Article_User_idUser` INT NOT NULL,
  PRIMARY KEY (`idInterest`, `Article_idArticle`, `Article_User_idUser`),
  INDEX `fk_Interest_Article1_idx` (`Article_idArticle` ASC, `Article_User_idUser` ASC),
  CONSTRAINT `fk_Interest_Article1`
    FOREIGN KEY (`Article_idArticle` , `Article_User_idUser`)
    REFERENCES `mydb`.`Article` (`idArticle` , `User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Skill` (
  `idSkill` INT NOT NULL,
  `skillName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSkill`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Skill` (
  `User_idUser` INT NOT NULL,
  `Skill_idSkill` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Skill_idSkill`),
  INDEX `fk_User_has_Skill_Skill1_idx` (`Skill_idSkill` ASC),
  INDEX `fk_User_has_Skill_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_User_has_Skill_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Skill_Skill1`
    FOREIGN KEY (`Skill_idSkill`)
    REFERENCES `mydb`.`Skill` (`idSkill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conversation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conversation` (
  `idConversation` INT NOT NULL,
  PRIMARY KEY (`idConversation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ParticipantsOfConversation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ParticipantsOfConversation` (
  `User_idUser` INT NOT NULL,
  `Conversation_idConversation` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Conversation_idConversation`),
  INDEX `fk_User_has_Conversation_Conversation1_idx` (`Conversation_idConversation` ASC),
  INDEX `fk_User_has_Conversation_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_User_has_Conversation_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Conversation_Conversation1`
    FOREIGN KEY (`Conversation_idConversation`)
    REFERENCES `mydb`.`Conversation` (`idConversation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Message` (
  `idMessage` INT NOT NULL,
  `contentText` TEXT(300) NOT NULL,
  `timeSent` DATETIME NOT NULL,
  `senderId` INT NOT NULL,
  `Conversation_idConversation` INT NOT NULL,
  PRIMARY KEY (`idMessage`, `Conversation_idConversation`),
  INDEX `fk_Message_Conversation1_idx` (`Conversation_idConversation` ASC),
  CONSTRAINT `fk_Message_Conversation1`
    FOREIGN KEY (`Conversation_idConversation`)
    REFERENCES `mydb`.`Conversation` (`idConversation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Advertisment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Advertisment` (
  `idAdvertisment` INT NOT NULL,
  `uploadTime` DATETIME NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `descriptionText` TEXT(3000) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idAdvertisment`, `User_idUser`),
  INDEX `fk_Advertisment_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Advertisment_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Application` (
  `idApplication` INT NOT NULL,
  `applicantId` VARCHAR(45) NOT NULL,
  `Advertisment_idAdvertisment` INT NOT NULL,
  `Advertisment_User_idUser` INT NOT NULL,
  PRIMARY KEY (`idApplication`, `Advertisment_User_idUser`, `Advertisment_idAdvertisment`),
  INDEX `fk_Application_Advertisment1_idx` (`Advertisment_idAdvertisment` ASC, `Advertisment_User_idUser` ASC),
  CONSTRAINT `fk_Application_Advertisment1`
    FOREIGN KEY (`Advertisment_idAdvertisment` , `Advertisment_User_idUser`)
    REFERENCES `mydb`.`Advertisment` (`idAdvertisment` , `User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Advertisment_has_Skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Advertisment_has_Skill` (
  `Advertisment_idAdvertisment` INT NOT NULL,
  `Advertisment_User_idUser` INT NULL,
  `Skill_idSkill` INT NOT NULL,
  PRIMARY KEY (`Advertisment_idAdvertisment`, `Skill_idSkill`),
  INDEX `fk_Advertisment_has_Skill_Skill1_idx` (`Skill_idSkill` ASC),
  INDEX `fk_Advertisment_has_Skill_Advertisment1_idx` (`Advertisment_idAdvertisment` ASC, `Advertisment_User_idUser` ASC),
  CONSTRAINT `fk_Advertisment_has_Skill_Advertisment1`
    FOREIGN KEY (`Advertisment_idAdvertisment` , `Advertisment_User_idUser`)
    REFERENCES `mydb`.`Advertisment` (`idAdvertisment` , `User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Advertisment_has_Skill_Skill1`
    FOREIGN KEY (`Skill_idSkill`)
    REFERENCES `mydb`.`Skill` (`idSkill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
